version: '3.5'

services:

  transactions-database:
    container_name: transactions-database
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /data/postgres
    ports:
      - "5432:5432"
    networks:
      - transactions-network
    restart: unless-stopped
  
  transactions-flyway:
    container_name: transactions-flyway
    image: flyway/flyway:9.7.0
    environment:
      - FLYWAY_EDITION=community
    command: -url=jdbc:postgresql://transactions-database:5432/${POSTGRES_DB} -schemas=${POSTGRES_DB} -user=${POSTGRES_USER} -password=${POSTGRES_PASSWORD} -connectRetries=50 migrate
    volumes:
      - ./migrations:/flyway/sql
    depends_on:
      - transactions-database
    networks:
      - transactions-network

networks:
  transactions-network:
    driver: bridge